// ============================================================
// STORMMESH -- MapAndAlerts Component
// Design: Tampa Bay flood zone map + prioritized alert feed + charts
// ============================================================

import { Alert, WeatherData, ThreatLevel, VULNERABILITY_ZONES, RESOURCES } from '@/lib/stormData';
import StormIntensityChart from './StormIntensityChart';
import VulnerabilityRadarChart from './VulnerabilityRadarChart';

const MAP_IMG = 'https://d2xsxph8kpxj0f.cloudfront.net/310519663488949635/H8uV2jDz2ia2afExqjD23w/stormmesh-map-overlay_d3cce59a.png';

interface MapAndAlertsProps {
  alerts: Alert[];
  weather: WeatherData;
  threatLevel: ThreatLevel;
}

const PRIORITY_CONFIG = {
  critical: { label: 'CRITICAL', color: '#EF4444', bg: 'rgba(239,68,68,0.1)', border: 'rgba(239,68,68,0.3)' },
  warning: { label: 'WARNING', color: '#F59E0B', bg: 'rgba(245,158,11,0.1)', border: 'rgba(245,158,11,0.3)' },
  advisory: { label: 'ADVISORY', color: '#06B6D4', bg: 'rgba(6,182,212,0.1)', border: 'rgba(6,182,212,0.3)' },
  info: { label: 'INFO', color: '#10B981', bg: 'rgba(16,185,129,0.1)', border: 'rgba(16,185,129,0.3)' }
};

const ZONE_STATUS_COLORS = {
  safe: '#10B981',
  watch: '#06B6D4',
  warning: '#F59E0B',
  evacuate: '#EF4444'
};

const RESOURCE_ICONS = {
  shelter: '🏟️',
  supply_depot: '📦',
  medical: '🏥',
  evacuation_route: '🛣️'
};

function AlertCard({ alert }: { alert: Alert }) {
  const cfg = PRIORITY_CONFIG[alert.priority];
  const timeAgo = Math.round((Date.now() - alert.timestamp.getTime()) / 60000);

  return (
    <div
      className="p-4 rounded-xl mb-3 transition-all duration-300"
      style={{
        background: cfg.bg,
        border: `1px solid ${cfg.border}`
      }}
    >
      <div className="flex items-start justify-between mb-2">
        <div className="flex items-center gap-2">
          <span
            className="text-xs font-mono font-bold px-2 py-0.5 rounded"
            style={{ background: `${cfg.color}20`, color: cfg.color }}
          >
            {cfg.label}
          </span>
          <span className="text-sm font-semibold" style={{ color: '#E2E8F0' }}>{alert.zone}</span>
        </div>
        <span className="text-xs font-mono" style={{ color: '#475569' }}>{timeAgo}m ago</span>
      </div>
      <p className="text-xs leading-relaxed mb-2" style={{ color: '#94A3B8' }}>{alert.message}</p>
      <div
        className="text-xs font-mono p-2 rounded"
        style={{ background: 'rgba(0,0,0,0.3)', color: '#60A5FA' }}
      >
        ▶ {alert.actionRequired}
      </div>
      {(alert.population ?? 0) > 0 && (
        <div className="flex items-center gap-1 mt-2">
          <span className="text-xs font-mono" style={{ color: '#475569' }}>
            {(alert.population ?? 0).toLocaleString()} residents affected
          </span>
          <span className="text-xs font-mono" style={{ color: '#334155' }}>·</span>
          <span className="text-xs font-mono" style={{ color: '#475569' }}>
            via {alert.agentSource}
          </span>
        </div>
      )}
    </div>
  );
}

export default function MapAndAlerts({ alerts, weather, threatLevel }: MapAndAlertsProps) {
  return (
    <section
      id="alerts"
      className="py-20"
      style={{ background: 'linear-gradient(to bottom, #040F1F, #020B18)' }}
    >
      <div className="max-w-[1400px] mx-auto px-6">
        {/* Section Header */}
        <div className="mb-12">
          <div
            className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-mono mb-4"
            style={{
              background: 'rgba(239, 68, 68, 0.1)',
              border: '1px solid rgba(239, 68, 68, 0.2)',
              color: '#F87171'
            }}
          >
            VULNERABILITY MAP & ALERT FEED
          </div>
          <h2
            className="text-4xl font-black mb-3"
            style={{ color: '#F1F5F9', fontFamily: "'Outfit', sans-serif" }}
          >
            Tampa Bay Threat Assessment
          </h2>
          <p className="text-base" style={{ color: '#64748B', maxWidth: '600px' }}>
            Real-time flood zone analysis, population vulnerability mapping, and prioritized
            evacuation orders generated by the Agent mesh.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
          {/* Map -- 3/5 */}
          <div className="lg:col-span-3">
            <div
              className="rounded-xl overflow-hidden relative"
              style={{
                border: '1px solid rgba(59,130,246,0.2)',
                height: '400px'
              }}
            >
              <img
                src={MAP_IMG}
                alt="Tampa Bay flood zone map"
                className="w-full h-full object-cover"
              />
              {/* Map overlay */}
              <div
                className="absolute inset-0"
                style={{
                  background: 'linear-gradient(to bottom, transparent 60%, rgba(2,11,24,0.8) 100%)'
                }}
              />

              {/* Zone legend */}
              <div
                className="absolute top-4 right-4 p-3 rounded-xl"
                style={{
                  background: 'rgba(2,11,24,0.85)',
                  backdropFilter: 'blur(12px)',
                  border: '1px solid rgba(59,130,246,0.2)'
                }}
              >
                <div className="text-xs font-mono font-semibold mb-2" style={{ color: '#64748B' }}>
                  FLOOD ZONES
                </div>
                {[
                  { label: 'Zone VE -- Extreme', color: '#EF4444' },
                  { label: 'Zone AE -- High', color: '#F59E0B' },
                  { label: 'Zone A -- Moderate', color: '#06B6D4' },
                  { label: 'Zone X -- Low', color: '#10B981' }
                ].map(z => (
                  <div key={z.label} className="flex items-center gap-2 mb-1">
                    <div className="w-3 h-2 rounded-sm" style={{ background: z.color, opacity: 0.8 }} />
                    <span className="text-xs font-mono" style={{ color: '#94A3B8' }}>{z.label}</span>
                  </div>
                ))}
              </div>

              {/* Storm info overlay */}
              <div
                className="absolute bottom-4 left-4 right-4 p-3 rounded-xl"
                style={{
                  background: 'rgba(2,11,24,0.9)',
                  backdropFilter: 'blur(12px)',
                  border: '1px solid rgba(239,68,68,0.3)'
                }}
              >
                <div className="flex items-center justify-between">
                  <div>
                    <div className="text-xs font-mono" style={{ color: '#64748B' }}>ACTIVE THREAT</div>
                    <div className="font-bold" style={{ color: '#F1F5F9' }}>
                      {weather.stormName} -- Category {weather.category}
                    </div>
                    <div className="text-xs font-mono mt-0.5" style={{ color: '#64748B' }}>
                      {weather.windSpeed} kt · Surge: {weather.surgeHeight}ft · Landfall: {weather.landfall}
                    </div>
                  </div>
                  <div className="text-right">
                    <div className="text-xs font-mono" style={{ color: '#64748B' }}>MOVEMENT</div>
                    <div className="text-sm font-mono font-semibold" style={{ color: '#F59E0B' }}>
                      {weather.movement}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Charts Row */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
              <StormIntensityChart />
              <VulnerabilityRadarChart />
            </div>

            {/* Vulnerability Zones Table */}
            <div
              className="mt-4 rounded-xl overflow-hidden"
              style={{
                background: 'rgba(10, 22, 40, 0.7)',
                border: '1px solid rgba(59,130,246,0.15)'
              }}
            >
              <div
                className="px-4 py-3"
                style={{ borderBottom: '1px solid rgba(59,130,246,0.1)' }}
              >
                <span className="text-xs font-mono font-semibold" style={{ color: '#94A3B8' }}>
                  VULNERABILITY ANALYSIS -- {VULNERABILITY_ZONES.length} ZONES
                </span>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-xs font-mono">
                  <thead>
                    <tr style={{ borderBottom: '1px solid rgba(59,130,246,0.08)' }}>
                      {['Zone', 'Flood', 'Pop.', 'Elderly', 'Low-Inc.', 'Risk', 'Status'].map(h => (
                        <th key={h} className="px-3 py-2 text-left" style={{ color: '#475569' }}>{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {VULNERABILITY_ZONES.map(zone => {
                      const statusColor = ZONE_STATUS_COLORS[zone.status];
                      return (
                        <tr
                          key={zone.id}
                          style={{ borderBottom: '1px solid rgba(59,130,246,0.05)' }}
                        >
                          <td className="px-3 py-2" style={{ color: '#CBD5E1' }}>{zone.name}</td>
                          <td className="px-3 py-2" style={{ color: '#64748B' }}>{zone.floodZone}</td>
                          <td className="px-3 py-2" style={{ color: '#94A3B8' }}>{zone.population.toLocaleString()}</td>
                          <td className="px-3 py-2" style={{ color: '#94A3B8' }}>{zone.elderlyPct}%</td>
                          <td className="px-3 py-2" style={{ color: '#94A3B8' }}>{zone.lowIncomePct}%</td>
                          <td className="px-3 py-2">
                            <div className="flex items-center gap-1.5">
                              <div
                                className="h-1.5 rounded-full"
                                style={{
                                  width: `${zone.riskScore * 0.5}px`,
                                  background: zone.riskScore > 80 ? '#EF4444' : zone.riskScore > 60 ? '#F59E0B' : '#10B981',
                                  maxWidth: '48px'
                                }}
                              />
                              <span style={{ color: '#E2E8F0' }}>{zone.riskScore}</span>
                            </div>
                          </td>
                          <td className="px-3 py-2">
                            <span
                              className="px-1.5 py-0.5 rounded text-xs uppercase"
                              style={{
                                background: `${statusColor}15`,
                                color: statusColor,
                                border: `1px solid ${statusColor}30`
                              }}
                            >
                              {zone.status}
                            </span>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {/* Right: Alerts + Resources -- 2/5 */}
          <div className="lg:col-span-2 flex flex-col gap-4">
            {/* Alert Feed */}
            <div
              className="flex-1 rounded-xl overflow-hidden"
              style={{
                background: 'rgba(10, 22, 40, 0.7)',
                border: '1px solid rgba(59,130,246,0.15)'
              }}
            >
              <div
                className="px-4 py-3 flex items-center justify-between"
                style={{ borderBottom: '1px solid rgba(59,130,246,0.1)' }}
              >
                <div className="flex items-center gap-2">
                  <div
                    className="w-2 h-2 rounded-full"
                    style={{
                      background: alerts.length > 0 ? '#EF4444' : '#475569',
                      animation: alerts.length > 0 ? 'agentPulse 1s ease-in-out infinite' : 'none',
                      boxShadow: alerts.length > 0 ? '0 0 6px #EF4444' : 'none'
                    }}
                  />
                  <span className="text-xs font-mono font-semibold" style={{ color: '#94A3B8' }}>
                    ALERT COMMANDER OUTPUT
                  </span>
                </div>
                <span className="text-xs font-mono" style={{ color: '#475569' }}>
                  {alerts.length} active
                </span>
              </div>
              <div className="p-4 overflow-y-auto" style={{ maxHeight: '440px' }}>
                {alerts.length === 0 ? (
                  <div className="text-center py-12">
                    <div className="text-3xl mb-3">🔔</div>
                    <div className="text-xs font-mono" style={{ color: '#475569' }}>
                      No active alerts
                    </div>
                    <div className="text-xs font-mono mt-1" style={{ color: '#334155' }}>
                      Launch simulation to generate alerts
                    </div>
                  </div>
                ) : (
                  alerts.map(alert => <AlertCard key={alert.id} alert={alert} />)
                )}
              </div>
            </div>

            {/* Resource Status */}
            <div
              className="rounded-xl overflow-hidden"
              style={{
                background: 'rgba(10, 22, 40, 0.7)',
                border: '1px solid rgba(16,185,129,0.15)'
              }}
            >
              <div
                className="px-4 py-3"
                style={{ borderBottom: '1px solid rgba(16,185,129,0.1)' }}
              >
                <span className="text-xs font-mono font-semibold" style={{ color: '#94A3B8' }}>
                  RESOURCE COORDINATOR STATUS
                </span>
              </div>
              <div className="p-3">
                {RESOURCES.map(res => {
                  const pct = res.capacity < 99999 ? Math.round((res.currentOccupancy / res.capacity) * 100) : 0;
                  const statusColor = res.status === 'available' ? '#10B981' : res.status === 'filling' ? '#F59E0B' : '#EF4444';
                  return (
                    <div
                      key={res.id}
                      className="flex items-center gap-3 p-2 rounded-lg mb-2"
                      style={{ background: 'rgba(0,0,0,0.2)' }}
                    >
                      <span className="text-base">{RESOURCE_ICONS[res.type]}</span>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between">
                          <span className="text-xs font-semibold truncate" style={{ color: '#CBD5E1' }}>
                            {res.name}
                          </span>
                          <span
                            className="text-xs font-mono ml-2 shrink-0"
                            style={{ color: statusColor }}
                          >
                            {res.status.toUpperCase()}
                          </span>
                        </div>
                        {res.capacity < 99999 && (
                          <div className="mt-1">
                            <div className="h-1 rounded-full overflow-hidden" style={{ background: 'rgba(255,255,255,0.08)' }}>
                              <div
                                className="h-full rounded-full transition-all duration-700"
                                style={{
                                  width: `${pct}%`,
                                  background: pct > 80 ? '#EF4444' : pct > 50 ? '#F59E0B' : '#10B981'
                                }}
                              />
                            </div>
                            <div className="text-xs font-mono mt-0.5" style={{ color: '#475569' }}>
                              {res.currentOccupancy.toLocaleString()} / {res.capacity.toLocaleString()}
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
